ARG BASE_UBI_IMAGE_TAG=9.6-1754584681
FROM registry.access.redhat.com/ubi9/ubi-minimal:${BASE_UBI_IMAGE_TAG}

ARG PYTHON_VERSION=3.12
ARG VLLM_VERSION=0.21.0

ENV VIRTUAL_ENV=/opt/vllm
ENV PATH=${VIRTUAL_ENV}/bin:$PATH

ENV VLLM_NO_USAGE_STATS=1
ENV VLLM_USE_V1=1
ENV VLLM_WORKER_MULTIPROC_METHOD=fork
ENV VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
ENV HF_HUB_OFFLINE=0
ENV OUTLINES_CACHE_DIR=/tmp/outlines
ENV VLLM_TARGET_DEVICE=cpu
ENV TORCHINDUCTOR_CPP_COMPILER=g++

# -----------------------------
# System dependencies
# -----------------------------
RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    microdnf install -y \
      python${PYTHON_VERSION} \
      python${PYTHON_VERSION}-pip \
      python${PYTHON_VERSION}-devel \
      util-linux \
      tar findutils \
      numactl numactl-devel \
      openblas openblas-devel \
      openmpi openmpi-devel \
      zeromq zeromq-devel \
      libsndfile \
      gcc \
      gcc-c++ \
      make \
      gperftools-libs \
      libtiff libjpeg-turbo openjpeg2 \
      libpng zlib \
      libwebp \
      freetype harfbuzz fribidi \
      lcms2 \
      libicu \
      openssl \
      && microdnf clean all

# -----------------------------
# Virtual environment
# -----------------------------
RUN python${PYTHON_VERSION} -m venv ${VIRTUAL_ENV}

RUN pip install --upgrade pip uv

# -----------------------------
# VLLM
# -----------------------------
RUN uv pip install \
      opencv-python-headless==4.13.0.92 \
      --extra-index-url https://wheels.developerfirst.ibm.com/ppc64le/linux/+simple/

RUN uv pip install \
      "vllm==${VLLM_VERSION}" \
      --extra-index-url https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.5-EA2/cpu-ubi9-test/simple/


ENV VLLM_CPU_MEMORY_UTILIZATION=0.65
ENV KMP_AFFINITY=granularity=fine,compact,1,0

# tcmalloc preload
ENV LD_PRELOAD=/usr/lib64/libtcmalloc.so.4

# -----------------------------
# User setup
# -----------------------------
RUN useradd --uid 2000 --gid 0 vllm && \
    mkdir -p /home/vllm && \
    chmod g+rwx /home/vllm

WORKDIR /home/vllm
USER 2000

ENTRYPOINT ["python", "-m", "vllm.entrypoints.openai.api_server"]
